import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"></BsFillMoonStarsFill>
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Jimmy Nguyen
            </h2>
            <h3 className="text-2xl py-2">Fontend Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              chua bit ghi j
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle></AiFillTwitterCircle>
            <AiFillLinkedin></AiFillLinkedin>
            <AiFillYoutube></AiFillYoutube>
          </div>

          <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden mx-auto">
            <Image src={deved} layout="fill" objectFit="cover"></Image>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">services i offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit,
              perferendis quidem!{" "}
              <span className="text-teal-500">
                Aut reprehenderit aspernatur
              </span>{" "}
              quam dolore quae nobis, doloremque alias deserunt sapiente
              incidunt distinctio fugiat, harum debitis asperiores? Asperiores,
              deserunt.
            </p>
          </div>

          <div>
            <div>
              <Image src={design}></Image>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
