import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin, AiFillYoutube } from "react-icons/ai";
import Image from "next/image";
import jimmy from "../public/jimmy.jpg";
import shopee from "../public/shopee.png";
import quanlinhanvien from "../public/quanlinhanvien.png";
import sassweb from "../public/sassweb.png";
import samar from "../public/samar.png";
import hoobank from "../public/hoobank.png";
import bootstrap from "../public/bootstrap.png";
import html from "../public/html5.svg";
import css from "../public/css-3.svg";
import bs from "../public/bootstrap-4.svg";
import sass from "../public/sass-1.svg";
import tail from "../public/tailwindcss.svg";
import js from "../public/JavaScript_logo.svg";
import ajax from "../public/ajax.png";
import axios from "../public/axios.png";
import github from "../public/github.png";
import es6 from "../public/es6.svg";

import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md-px-20 lg:px-40 dark:bg-gray-900 dark:text-white ">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">welcome my portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                ></BsFillMoonStarsFill>
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md ml-8 text-white"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="md:flex">
            <div className="mx-auto overflow-hidden mt-20 md:w-80 sm:w-40">
              <Image src={jimmy} className="rounded-lg"></Image>
            </div>

            <div className="text-center p-10 ">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl ">
                Lý Vĩnh Phú ( Jimmy )
              </h2>
              <h3 className="text-2xl py-2 md:text-3xl">Fontend Developer</h3>
              <p
                className="text-md text-left py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto
            dark:text-gray-300"
              >
                Good day, everyone! I'm often passionate about learning new
                technologies and always keep concentrated on improving my self
                skills. Being patient and responsible for working help me
                implement completely assigned tasks.
              </p>
              <p
                className="text-md text-left py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto
            dark:text-gray-300"
              >
                I always put my heart and soul into every single website that I
                develop. I guess that's all I have to share about myself. Hope
                that I can contribute to the development of your company. Thank
                you for reading!
              </p>
            </div>
          </div>

          <div className="text-6xl flex justify-center gap-16 py-3 text-gray-600  ">
            <a href="https://github.com/JimmyNguyen22" target="_blank">
              <AiFillGithub></AiFillGithub>
            </a>
            <a
              href="https://www.linkedin.com/in/v%C4%A9nh-ph%C3%BA-7156b9247/"
              target="_blank"
            >
              <AiFillLinkedin></AiFillLinkedin>
            </a>
            <a href="#">
              <AiFillYoutube></AiFillYoutube>
            </a>
          </div>
        </section>

        <section>
          <h1 className="text-4xl py-1">My Skills</h1>
          <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-300">
            Basic knowledge of{" "}
            <span className="text-teal-500">
              HTML5, CSS3, Boostrap 5, SCSS, Javascript (ES5/ES6), AJAX,
              RESTfull API, OOP, Git
            </span>{" "}
          </p>
          <div className="shadow-lg p-10 rounded-xl my-10 dark:bg-gray-300 w-max	">
            <div className="flex gap-10 items-center">
              <span>
                <Image src={html} width={50} height={50}></Image>
              </span>
              <span>
                <Image src={css} width={50} height={50}></Image>
              </span>
              <span>
                <Image src={bs} width={50} height={50}></Image>
              </span>
              <span>
                <Image src={sass} width={50} height={50}></Image>
              </span>
              <span>
                <Image src={tail} width={50} height={50}></Image>
              </span>
            </div>

            <div className="flex gap-10 items-center mt-5">
              <span>
                <Image src={js} width={50} height={50}></Image>
              </span>
              <span>
                <Image src={es6} width={50} height={50}></Image>
              </span>
              <span>
                <Image src={ajax} width={50} height={50}></Image>
              </span>
              <span>
                <Image src={axios} width={50} height={50}></Image>
              </span>
              <span>
                <Image src={github} width={50} height={50}></Image>
              </span>
            </div>
          </div>
        </section>

        <section>
          <h1 className="text-4xl py-1 mt-10">My Projects</h1>

          <div className="flex flex-col gap-7 py-10 lg:flex-row lg:flex-wrap">
            <div className="w-[380px]	shadow-lg overflow-hidden rounded-xl dark:bg-gray-800">
              <Image
                src={shopee}
                className=" rounded-xl object-cover h-[250px]"
                layout="reponsive"
              ></Image>
              <div className="p-5">
                <div className="text-2xl text-teal-500 uppercase text-center mb-3">
                  <h1>Shopee</h1>
                </div>
                <p className="text-lg">
                  <span className="text-teal-600 text-xl">- Description:</span>{" "}
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. P
                </p>{" "}
                <p className="text-lg">
                  <span className="text-teal-600 text-xl">- Technology:</span>{" "}
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. P
                </p>
              </div>
              <div className="flex justify-between gap-5 pb-5 pl-5 pr-5">
                <a
                  href="https://github.com/JimmyNguyen22/shopeeJs"
                  target="_blank"
                  className="bg-gradient-to-r min-w-[147px] text-center from-cyan-500 to-teal-500 px-4 py-2 rounded-md text-white"
                >
                  Link Github
                </a>

                <a
                  href="https://jimmynguyen22.github.io/shop/shopee.html"
                  target="_blank"
                  className="bg-red-600 min-w-[147px] text-center px-4 py-2 rounded-md text-white"
                >
                  Link Demo
                </a>
              </div>
            </div>

            <div className="	w-[380px]	shadow-lg overflow-hidden rounded-xl dark:bg-gray-800">
              <Image
                src={quanlinhanvien}
                className="rounded-xl object-cover h-[250px]"
                layout="reponsive"
              ></Image>
            </div>
            <div className="	w-[380px]	shadow-lg overflow-hidden rounded-xl dark:bg-gray-800 ">
              <Image
                src={sassweb}
                className="rounded-xl object-cover h-[250px]"
                layout="reponsive"
              ></Image>
            </div>
            <div className="w-[380px]	shadow-lg overflow-hidden rounded-xl	dark:bg-gray-800 ">
              <Image
                src={samar}
                className="rounded-xl object-cover h-[250px]"
                layout="reponsive"
              ></Image>
            </div>
            <div className="w-[380px]	shadow-lg overflow-hidden rounded-xl	dark:bg-gray-800 ">
              <Image
                src={bootstrap}
                className="rounded-xl object-cover h-[250px]"
                layout="reponsive"
              ></Image>
            </div>
            <div className="w-[380px]	shadow-lg overflow-hidden rounded-xl dark:bg-gray-800	 ">
              <Image
                src={hoobank}
                className="rounded-xl object-cover h-[250px]"
                layout="reponsive"
              ></Image>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
